import React from 'react';
import { ArrowRight, BarChart3, BookOpen, Brain, CheckCircle2, ChevronRight, Clock3, FileText, ListChecks, PenTool, Play, Route, ShieldCheck, Sparkles, Target } from 'lucide-react';
import { syllabus } from '../data/syllabus.js';
import { lessons } from '../data/lessons.js';
import { mockTests, studyMilestones } from '../data/appPages.js';
import { CoursesPreview, LearningMap } from './CourseMap.jsx';
import { DashItem, ExamStats, Feature, PageHeader, Quiz, SectionHead, Step } from './common.jsx';

export function HomePage({ go, startLesson }) { return <><section className="hero appHero"><div className="heroCopy"><div className="eyebrow"><Sparkles size={16} /> Interactive exam prep</div><h1>Learn RPSC Lecturer English by solving tiny challenges.</h1><p className="lede">A premium, practice-first study app for grammar, literature, theory, pedagogy and ICT — built around active recall, explanations and exam discipline.</p><div className="heroActions"><button className="btn primary" onClick={() => go('courses')}>Explore course map <ArrowRight size={18} /></button><button className="btn secondary" onClick={() => startLesson(lessons[0])}>Try first lesson</button></div><div className="trustRow"><span><ShieldCheck size={17} /> Syllabus aligned</span><span><Target size={17} /> MCQ focused</span><span><Clock3 size={17} /> Built for revision</span></div></div><div className="learningPreview" aria-label="Learning path preview"><div className="previewTop"><span>Today’s path</span><strong>12 min</strong></div><div className="previewProblem"><small>Challenge</small><h3>Choose the correct article:</h3><p>He is ___ honest man.</p><div className="previewOptions"><span>a</span><span className="selected">an</span><span>the</span></div></div><div className="previewExplain"><CheckCircle2 size={18} /> Learn from the explanation, not just the answer.</div></div></section><ExamStats /><section className="section"><SectionHead kicker="Learning experience" title="Short lessons. Immediate questions. Clear explanations." text="Instead of dumping notes, the app guides learners through a map of small concepts and makes them answer before reading the explanation." /><div className="featureGrid"><Feature icon={<Route />} title="Course map" text="A visible path through grammar, literature, theory and pedagogy." /><Feature icon={<ListChecks />} title="Challenge-first" text="Every lesson asks the learner to think before revealing the rule." /><Feature icon={<Brain />} title="Error-aware" text="MCQ explanations focus on traps and negative-marking risk." /><Feature icon={<BarChart3 />} title="Mock-ready" text="The structure is ready for section tests and full paper simulations." /></div></section><LearningMap lessons={lessons} startLesson={startLesson} compact /></>; }
export function CoursesPage({ go, startLesson }) { return <><PageHeader pageId="courses" icon={<BookOpen />} /><CoursesPreview go={go} full /><LearningMap lessons={lessons} startLesson={startLesson} /></>; }
export function PracticePage({ activeLesson, setActiveLesson, answers, setAnswers, answerKey, score }) { const firstQuestion = activeLesson.quiz[0]; return <><PageHeader pageId="practice" icon={<PenTool />} /><section className="lessonWorkspace compactTop"><aside className="lessonSidebar"><span className="kicker">Lesson path</span><div className="miniProgress"><strong>{score}</strong><span>correct answers</span></div><div className="lessonTabs">{lessons.map((lesson, index) => <button key={lesson.id} className={lesson.id === activeLesson.id ? 'lessonTab active' : 'lessonTab'} onClick={() => setActiveLesson(lesson)}><span>Step {index + 1} · {lesson.track}</span>{lesson.title}<small>{lesson.difficulty} · {lesson.minutes} min</small></button>)}</div></aside><article className="challengeCard"><div className="lessonMeta"><span>{activeLesson.track}</span><small>{activeLesson.difficulty}</small></div><h2>{activeLesson.title}</h2><p className="principle">{activeLesson.principle}</p><div className="conceptStrip"><Step index="01" title="Idea" text={activeLesson.concept} /><Step index="02" title="Example" text={activeLesson.example} /><Step index="03" title="Trap" text={activeLesson.misconception} /></div><div className="challengePrompt"><small>Interactive checkpoint</small><h3>{activeLesson.prompt}</h3><details><summary>Show guided explanation</summary><p>{activeLesson.answer}</p></details></div><div className="quizBlock"><h3>Solve it</h3>{firstQuestion && <Quiz item={firstQuestion} selected={answers[answerKey(activeLesson.id, 0)]} onSelect={(isCorrect) => setAnswers({ ...answers, [answerKey(activeLesson.id, 0)]: isCorrect })} />}{activeLesson.quiz.slice(1).map((item, idx) => <Quiz key={idx + 1} item={item} selected={answers[answerKey(activeLesson.id, idx + 1)]} onSelect={(isCorrect) => setAnswers({ ...answers, [answerKey(activeLesson.id, idx + 1)]: isCorrect })} />)}</div></article></section></>; }
export function MockTestsPage({ go }) { return <><PageHeader pageId="mock-tests" icon={<FileText />} /><ExamStats /><section className="section compactTop"><div className="mockGrid">{mockTests.map((test) => <article className="mockCard" key={test.id}><span className="miniLabel">{test.status}</span><h3>{test.title}</h3><p>{test.purpose}</p><div className="mockMeta"><strong>{test.questions} questions</strong><strong>{test.duration}</strong></div><button className="btn primary" onClick={() => go('practice')}>Prepare first <ArrowRight size={17} /></button></article>)}</div></section></>; }
export function SyllabusPage() { return <><PageHeader pageId="syllabus" icon={<ListChecks />} /><section className="section compactTop syllabusSection"><div className="syllabusGrid">{syllabus.map((part) => <article className="syllabusCard" key={part.id}><span className="part">{part.part}</span><h3>{part.title}</h3><p>{part.weightHint}</p><details open><summary>{part.topics.length} topics <ChevronRight size={16} /></summary><ul>{part.topics.map((topic) => <li key={topic}>{topic}</li>)}</ul></details></article>)}</div></section></>; }
export function StudyPlanPage({ go }) { return <><PageHeader pageId="study-plan" icon={<Route />} /><section className="studyPlan standalone"><div><span className="kicker">Recommended route</span><h2>Start with accuracy. Then build recall speed.</h2><p>Because the paper has negative marking, the goal is confident selection under time pressure.</p></div><ol>{studyMilestones.map((m) => <li key={m.week}><strong>{m.week}: {m.focus}</strong><br />{m.action}</li>)}</ol><button className="btn primary" onClick={() => go('practice')}><Play size={17} /> Continue practice</button></section></>; }
